name: ddpm

model:
  arch:
    _target_: core.module.wrapper.ema.EMA
    model:
      _target_: core.module.modules.unet.AE_CNN_bottleneck
      in_channel: 1
      in_dim: 52

#     model:
#       _target_: core.module.modules.od_unet.AE_CNN_bottleneck
#       in_dim: 52

  data_transform:
    system_cls:
      _target_: core.system.encoder.EncoderSystem
    checkpoint_path:

train:
  optimizer:
    _target_: torch.optim.AdamW
    lr: 1e-3
    weight_decay: 2e-6

  lr_scheduler:

  trainer:
    _target_:  pytorch_lightning.trainer.Trainer
    _convert_: all
    max_epochs: 10000
    check_val_every_n_epoch: 500
    val_check_interval : 500
    log_every_n_steps: 10
    limit_val_batches: 1
    limit_test_batches: 1
    devices:
      - ${device.id}

    enable_model_summary: false

    callbacks:
      - _target_: core.module.pl.callbacks.modelCheckpoint
        monitor: 'best_g_acc'
        mode: 'max'
        save_top_k: 3
        save_last: true
        filename: 'ddpm_{epoch}-{best_g_acc:.4f}_{mean_g_acc:.4f}'


    logger:
      _target_: core.module.pl.callbacks.tensorBoardLogger
      save_dir: ${output_dir}
      name: 'tensorboard'

